export default {
    SAMPLE: 'SAMPLE',
    ADD_LETTER: 'ADD_LETTER',
    RESET_TIMER: 'REST_TIMER',
    REMOVE_LAST_LETTER: 'REMOVE_LAST_LETTER',
    REQUEST_STARTED: 'REQUEST_STARTED',
    RECEIVED_WORDS: 'RECEIVED_WORDS',
    ADD_TO_SENTENCE: 'ADD_TO_SENTECE'
}